name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on: [push]
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Run build script
        run: ./.github/scripts/something.sh
        shell: bash
